.TH solaar 1 "June 06, 2014" solaar
.SH NAME
solaar \- wireless Logitech device manager
.SH SYNOPSIS
.B solaar
[\fIoptions\fP]
.SH DESCRIPTION
.B solaar
is a device manager for Logitech wireless devices (keyboards and
mice). It supports many recent Unifying devices, allows pairing and
unpairing devices, querying the battery level, and configuring various
features such as smooth scrolling, side scrolling...
.PP
.SH OPTIONS
.B solaar
accepts the following options:
.TP
.BR \-h ", " \-\-help
Displays a brief help message and quits.
.TP
.BR \-d ", " \-\-debug
Starts the graphical device manager and prints logging messages during
execution.
.TP
.BR \-V ", " \-\-version
Displays the program's version number and quits.
.PP
Without options, starts the graphical device manager if it is not
already running, or displays the configuration screen if it is.
.SH AUTHORS
\fBsolaar\fP was written by Daniel Pavel.

This manual page was written by Stephen Kitt <skitt@debian.org>, for
the Debian GNU/Linux system (but may be used by others). It was last
modified for \fBsolaar\fP version 0.9.2.

